services:
  bot:
    build:
      context: ../app
      dockerfile: ../.docker/Dockerfile
      target: ${DOCKER_TARGET:-dev} # Для dev-режима используем отдельный build target
    container_name: password-halop-bot
    restart: unless-stopped
    env_file:
      - .env # В dev-режиме удобно использовать .env
    depends_on:
      - db
    volumes:
      - ../app:/app # Для hot reload и локальной разработки
      - ../app/tmp:/app/tmp # Для бинарных файлов
    ports:
      - "6060:6060"

  db:
    image: postgres:15-alpine
    container_name: password-halop-db
    restart: unless-stopped
    env_file:
      - .env # Переменные для базы также через .env
    ports:
      - "${PUBLIC_POSTGRES_PORT}:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data

#volumes:
#  pgdata: